Fix/multiple latched publishers
Intermodalics/ros_comm pull request #1
Opened 2018-11-19 09:56 UTC by achim-k

2018-11-20 01:24 UTC, meyerj requested changes
Functionally looks good. One minor comment about CMake 3.0 compatibility of the added unit test. Please also add a BSD license header following the example from other unit tests.

2018-11-20 01:24 UTC, meyerj commented on test/test_roscpp/test/src/CMakeLists.txt
> +set_property(TARGET ${PROJECT_NAME}-multiple_latched_publishers PROPERTY CXX_STANDARD 11)
The `CXX_STANDARD` target property [was introduced with CMake 3.1](https://cmake.org/cmake/help/v3.1/release/3.1.0.html#properties), but kinetic targets CMake 3.0.2 according to [REP-3](http://www.ros.org/reps/rep-0003.html#kinetic-kame-may-2016-may-2021).

I suggest to use
```cmake
if(NOT WIN32)
  target_compile_options(${PROJECT_NAME}-multiple_latched_publishers PRIVATE "-std=c++11")
endif()
```
instead, following the example in [roscpp/CMakeLists.txt:4-6](https://github.com/Intermodalics/ros_comm/blob/8bbbcbc183beb9c4c43ebb26405cae9bcb96284b/clients/roscpp/CMakeLists.txt#L4-L6) (for a single target).

2018-11-20 10:32 UTC, achim-k commented on test/test_roscpp/test/src/CMakeLists.txt
> +set_property(TARGET ${PROJECT_NAME}-multiple_latched_publishers PROPERTY CXX_STANDARD 11)
This is targeting `melodic-devel` since it's the default branch. So I guess using `CXX_STANDARD` would be OK, no?

2018-11-20 14:57 UTC, meyerj commented on test/test_roscpp/test/src/CMakeLists.txt
> +set_property(TARGET ${PROJECT_NAME}-multiple_latched_publishers PROPERTY CXX_STANDARD 11)
Yes, you are right. It would only be relevant if this patch will be backported to kinetic, which is unlikely.

2018-11-20 19:51 UTC, meyerj commented on test/test_roscpp/test/src/CMakeLists.txt
> + add_dependencies(${PROJECT_NAME}-multiple_latched_publishers ${${PROJECT_NAME}_EXPORTED_TARGETS})
nit: leading space

2018-11-21 11:39 UTC, meyerj approved these changes

2018-11-22 19:13 UTC, merged